export const accessToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywibmFtZSI6IlRlc3RlIE9saXZlaXJhIiwiZW1haWwiOiJtYXRldXNvNDQ0QGdtYWlsLmNvbSIsImlhdCI6MTcyMzcyOTYyOCwiZXhwIjoxNzI0MzM0NDI4LCJhdWQiOiJ1c2VycyIsImlzcyI6ImxvZ2luIiwic3ViIjoiNyJ9.qtRscHmi1o_sr5r6qom1gS9AVLfEqs2SLiUygyy2Fxo';
